[general]
import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
startup_mode = "Maximized"
opacity = 1

padding.x = 8
padding.y = 8

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Mononoki Custom Mono"
normal.style = "Regular"
