import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]

[window]
startup_mode = "Maximized"
opacity = 1

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "Mononoki Nerd Font Mono"
#bold.family = ""
#italic.family = ""
#bold_italic.family = ""

#size = 15.0
